# SPDX-License-Identifier: MIT
"""Upload a finished export to a Corpus library.

Corpus is a private library: a catalogue harvested from elsewhere, plus whatever
its owner puts in by hand. `POST /book/upload` is the second door — the one a
PDF of a course, an EPUB bought elsewhere, a Markdown file out of OCR, or an
Aglaïa OCR textpack (`<stem>_OCR.textpack`) comes through.

    POST {base}/book/upload
    X-API-Key: …
    multipart: file=@… [title] [author] [publisher] [language] [year]
                       [pages] [categories]

Everything but `file` is optional; without a title the filename is used. Since
Aglaïa already knows the document's metadata, it sends it — retyping a title
into a web form is exactly the tedium this destination exists to remove.

The API answers with four outcomes that mean four different things, and this
plugin keeps them four rather than flattening them into ok/failed:

    201 added     the reply carries id, path, bytes
    200 exists    the corpus already has it (its own rule: same sha-256, or
                  same title and author); nothing written
    400 refuse    extension not admitted, an empty file, or a malformed
                  textpack (body: message + detail/reason)
    413 refuse    over 2 GiB — or over 100 MB behind Cloudflare
    422 refuse    a textpack's `corpus.zlib_id` names no book

`200 exists` is not an error — the book is in the library, which is what the
user wanted. Reporting it as a failure would teach him to ignore failures.
"""

from __future__ import annotations

from pathlib import Path

from aglaia.plugin_api import (
    BookMeta, CheckResult, Destination, Field, SendResult, http_client,
    register_destination,
)

#: What the fiching chain can read, per the API docs. Sending anything else
#: gets a 400, so it is refused locally with a message that names the list —
#: a round trip to be told "no" is a round trip wasted.
ADMITTED = ("pdf", "epub", "djvu", "md", "txt", "docx", "doc", "odt", "rtf",
            "mobi", "azw3", "fb2", "html", "textpack")


@register_destination
class CorpusDestination(Destination):
    name = "send-to-corpus"
    display = "Export to Corpus library"
    description = "Upload the export to a Corpus library instance."
    # Both the PDF and the Markdown export are admitted, so both are offered.
    # `textpack` is Aglaïa's OCR textpack (source.pdf + text.md + raw OCR,
    # yb85/aglaia#148): corpus files it under downloads/ocr/ by its
    # `_OCR.textpack` suffix. Its info.json carries OCR provenance, not the
    # catalogue record, so the metadata fields below are still sent.
    accepts = ("pdf", "md", "txt", "epub", "html", "textpack")

    CONFIG_FIELDS = (
        # No default, and a placeholder that is not anybody's address. A
        # Corpus instance is a PRIVATE library; baking one installation's
        # hostname into a public registry publishes it to everyone who reads
        # the plugin. Required, so the user supplies their own.
        Field("base_url", "Corpus URL", "str", "", required=True,
              placeholder="https://corpus.example.org",
              help="Your Corpus instance. Include the scheme."),
        Field("default_language", "Default language", "str", "",
              placeholder="French",
              help="Used when the project does not say."),
        Field("default_categories", "Default categories", "str", "",
              placeholder="Ecclésiologie",
              help="Used when the project does not say."),
        Field("timeout_s", "Timeout (seconds)", "int", 300,
              help="Maximum upload size is 2 GiB."),
    )
    SECRET_FIELDS = (
        Field("api_key", "API key", "secret", "", required=True,
              help="Generated by your Corpus instance."),
        Field("extra_headers", "Additional headers", "headers",
              help="Only if your corpus sits behind something that asks for "
                   "its own credentials. Add one header at a time: its name, "
                   "then its value."),
    )

    # ── plumbing ──────────────────────────────────────────────────────
    def _root(self) -> str:
        return str(self.conf("base_url") or "").strip().rstrip("/")

    def _headers(self) -> dict:
        # The API key, plus whatever the user added — a corpus can sit behind
        # an authenticating proxy that wants headers of its own (Cloudflare
        # Access: CF-Access-Client-Id + CF-Access-Client-Secret).
        head = {"X-API-Key": self.secret("api_key")}
        head.update(self.headers("extra_headers"))
        return head

    def _client(self):
        # The host's client: IPv4-preferring, so a dead IPv6 route does not
        # cost 24 s per request (see aglaia/net.py).
        #
        # `follow_redirects=False` is the important part. The host's default
        # follows them, and an authenticating proxy answers 302 towards its
        # own login page — which returns 200 and an HTML form. Followed, that
        # reads as a successful corpus answer: a send that never reached the
        # corpus was reported as "already present" (Delbrêl, t. X). A
        # redirect is now an answer in itself, and it is not a success.
        return http_client(float(self.conf("timeout_s") or 300),
                           follow_redirects=False)

    @staticmethod
    def _blocked_by(r) -> str:
        """The proxy that refused this request, or "" if none did.

        Recognises the shape, not one vendor: a redirect away from the
        corpus, or an HTML page where JSON was promised, is an authentication
        wall whatever its name."""
        target = r.headers.get("location", "") if r.status_code in (
            301, 302, 303, 307, 308) else ""
        body_head = ""
        if not target:
            ctype = (r.headers.get("content-type") or "").lower()
            if "html" in ctype:
                body_head = (r.text or "")[:400]
        blob = f"{target} {body_head}".lower()
        if not blob.strip():
            return ""
        if "cloudflareaccess.com" in blob or "cdn-cgi/access" in blob:
            return "Cloudflare Access"
        if target:
            return "a redirect"
        return "an HTML page"

    @staticmethod
    def _access_meta(location: str) -> dict:
        """What Cloudflare Access itself says about this refusal.

        Its redirect carries a `meta` JWT whose payload names what it saw —
        `service_token_status` in particular. The payload is read, never
        trusted and never verified: it is the proxy's own account, and it is
        the difference between "you sent no token" and "your token was not
        accepted", which are two different things for the user to fix."""
        import base64
        import json as _json
        from urllib.parse import parse_qs, urlparse
        got = parse_qs(urlparse(location).query).get("meta") or []
        if not got:
            return {}
        parts = got[0].split(".")
        if len(parts) < 2:
            return {}
        raw = parts[1] + "=" * (-len(parts[1]) % 4)
        try:
            out = _json.loads(base64.urlsafe_b64decode(raw))
        except Exception:
            return {}
        return out if isinstance(out, dict) else {}

    def _wall(self, r, where: str) -> tuple[str, dict]:
        """Message + detail for a request an authentication wall stopped."""
        who = self._blocked_by(r)
        target = r.headers.get("location", "")
        if who == "Cloudflare Access":
            sent = sorted(self.headers("extra_headers"))
            meta = self._access_meta(target)
            token_ok = meta.get("service_token_status")
            if not sent:
                msg = (f"Cloudflare Access refuses the request to {where}: a "
                       f"service token is missing. Add CF-Access-Client-Id "
                       f"and CF-Access-Client-Secret under Additional "
                       f"headers.")
            elif token_ok is False:
                msg = (f"Cloudflare Access refuses the request to {where}. "
                       f"It was sent {', '.join(sent)} and Access reports no "
                       f"valid service token, so the pair is wrong, or that "
                       f"token is not on this application with a policy "
                       f"whose action is Service Auth.")
            else:
                msg = (f"Cloudflare Access refuses the request to {where}, "
                       f"although {', '.join(sent)} went with it. Check the "
                       f"token pair and the application's policy.")
        elif who:
            msg = (f"{where} did not answer as a corpus — {who} came back "
                   f"instead. The address may be wrong, or something is "
                   f"asking this machine to sign in.")
        else:
            msg = f"{where} answered {r.status_code} with no corpus reply."
        detail = {"status": r.status_code, "location": target,
                  "content_type": r.headers.get("content-type", "")}
        if who == "Cloudflare Access":
            meta = self._access_meta(target)
            detail["sent_headers"] = sorted(self.headers("extra_headers"))
            detail["service_token_status"] = meta.get("service_token_status")
            detail["auth_status"] = meta.get("auth_status")
        return msg, detail

    @staticmethod
    def _corpus_json(r):
        """The corpus's own JSON answer, or None if this is not one.

        A corpus answer is JSON carrying `status`. Anything else — an HTML
        login form, a proxy's error page, a bare 200 — is not an answer about
        a book, and must never be read as one."""
        if "json" not in (r.headers.get("content-type") or "").lower():
            return None
        try:
            body = r.json()
        except Exception:
            return None
        return body if isinstance(body, dict) and "status" in body else None

    # ── check ─────────────────────────────────────────────────────────
    def check(self) -> CheckResult:
        """`/healthz` is the one open route, so it separates "the instance is
        down" from "the key is wrong" — and those have nothing to do with each
        other. Then an authenticated call proves the key."""
        import httpx
        root = self._root()
        if not root:
            return CheckResult(False, "No corpus URL set.",
                               kind=CheckResult.CONFIG)
        try:
            with self._client() as c:
                health = c.get(f"{root}/healthz")
        except httpx.HTTPError as e:
            return CheckResult(
                False, f"Could not reach {root}.",
                {"error": f"{type(e).__name__}: {e}"},
                kind=CheckResult.NETWORK)
        if self._blocked_by(health) or health.status_code in (
                301, 302, 303, 307, 308):
            msg, detail = self._wall(health, root)
            return CheckResult(False, msg, detail, kind=CheckResult.AUTH)
        if health.status_code >= 400:
            return CheckResult(
                False, f"{root} is running, but reports a problem.",
                {"status": health.status_code, "route": "/healthz"},
                kind=CheckResult.SERVER)
        if not self.secret("api_key"):
            return CheckResult(False, "Reachable, but no API key set.",
                               kind=CheckResult.CONFIG)
        try:
            with self._client() as c:
                r = c.get(f"{root}/openapi.json", headers=self._headers())
        except httpx.HTTPError as e:
            return CheckResult(False, "Lost the connection while signing in.",
                               {"error": f"{type(e).__name__}: {e}"},
                               kind=CheckResult.NETWORK)
        if self._blocked_by(r) or r.status_code in (301, 302, 303, 307, 308):
            msg, detail = self._wall(r, f"{root}/openapi.json")
            return CheckResult(False, msg, detail, kind=CheckResult.AUTH)
        if r.status_code in (401, 403):
            return CheckResult(False, "The API key was rejected.",
                               {"status": r.status_code},
                               kind=CheckResult.AUTH)
        if r.status_code >= 400:
            return CheckResult(False, f"Authenticated call answered "
                                      f"{r.status_code}.")
        return CheckResult(True, f"Connected to {root}; key accepted.")

    # ── send ──────────────────────────────────────────────────────────
    def send(self, path: Path, meta: BookMeta) -> SendResult:
        import httpx
        path = Path(path)
        if not path.is_file():
            return SendResult(False, f"No such file: {path}")
        ext = path.suffix.lower().lstrip(".")
        if ext not in ADMITTED:
            return SendResult(
                False, f".{ext} is not admitted by the corpus. It takes: "
                       f"{', '.join(ADMITTED)}.")
        if path.stat().st_size == 0:
            return SendResult(False, f"{path.name} is empty.")
        root = self._root()
        if not root:
            return SendResult(False, "No corpus URL set.")
        if not self.secret("api_key"):
            return SendResult(False, "No API key set.")

        # Only fields that have a value: an empty field means "erase this" to
        # the metadata route, and the same habit here would send blanks that
        # overwrite a harvested record with nothing.
        fields = meta.filled()
        fields.setdefault("language",
                          str(self.conf("default_language") or "").strip())
        fields.setdefault("categories",
                          str(self.conf("default_categories") or "").strip())
        data = {k: v for k, v in fields.items() if v}

        try:
            with self._client() as c, path.open("rb") as fh:
                r = c.post(f"{root}/book/upload",
                           headers=self._headers(),
                           files={"file": (path.name, fh,
                                           "application/octet-stream")},
                           data=data)
        except httpx.HTTPError as e:
            return SendResult(False, f"Upload failed — {type(e).__name__}: {e}")

        # Before anything else: did a corpus answer at all? A proxy's
        # redirect or login page is not an answer about this book.
        if self._blocked_by(r) or r.status_code in (301, 302, 303, 307, 308):
            msg, detail = self._wall(r, f"{root}/book/upload")
            return SendResult(False, msg, detail=detail)
        if r.status_code in (401, 403):
            return SendResult(False, "The corpus rejected the API key.")

        body = self._corpus_json(r) or {}
        where = body.get("instance") or {}
        who = str(where.get("host") or root)

        if r.status_code == 413:
            # Two ceilings: the corpus's own 2 GiB, and 100 MB when the
            # instance sits behind Cloudflare — which is the one a scanned
            # book's textpack usually meets.
            size_mb = path.stat().st_size / 1e6
            return SendResult(
                False, f"{path.name} ({size_mb:.0f} MB) is too large for this "
                       f"corpus address. Behind Cloudflare the limit is "
                       f"100 MB: use the corpus's local network address "
                       f"instead.", detail=body)
        if r.status_code == 422:
            # Only a textpack names a book: `corpus.zlib_id` in its info.json.
            why = body.get("message") or body.get("detail") or ""
            return SendResult(
                False, "The corpus has no book with the zlib id this textpack "
                       "names. Check the id, or export without one to add it "
                       "as a new book." + (f" ({why})" if why else ""),
                detail=body)

        if r.status_code == 200 and not body:
            # 200 with no corpus JSON: something answered in its place.
            msg, detail = self._wall(r, f"{root}/book/upload")
            return SendResult(False, msg, detail=detail)

        if r.status_code == 200:
            # Name the corpus and the book it matched. A bare "already there"
            # is unfalsifiable: a volume of a series can match its siblings on
            # title alone, and the user then has no way to see that the match
            # is wrong, nor which instance answered (a stale address answers
            # like a current one). Whatever the corpus says it matched goes in
            # the message.
            got = body.get("title") or body.get("detail") or body.get("message")
            got_id = body.get("id")
            why = body.get("reason")
            which = f" — it matched {got!r}" if got else ""
            which += f" (#{got_id})" if got_id else ""
            which += f", on {why}" if why else ""
            return SendResult(
                True, f"{who} already has {meta.title or path.name}{which}. "
                      f"Nothing was written. If that is a different book, "
                      f"check the title and the address above.",
                already_there=True, detail=body)
        if r.status_code == 201:
            book_id = body.get("id")
            link = f"{root}/book/{book_id}" if book_id else ""
            return SendResult(
                True, f"Uploaded to {who}"
                      + (f" as #{book_id}." if book_id else "."),
                url=link, detail=body)
        if r.status_code == 400:
            why = (body.get("message") or body.get("detail")
                   or body.get("reason") or r.text[:200])
            return SendResult(False, f"The corpus refused it: {why}")
        return SendResult(False, f"The corpus answered {r.status_code}: "
                                 f"{r.text[:200]}")
